### ISSUE TITLE
Can't compile on mac os yosemite

### ISSUE THREAD

**Issue by max107** [allanks/Voxel-Engine#43]
imports changed from `github.com/go-gl/glow/gl-core/4.5/gl` to `github.com/go-gl/gl/v4.5-core/gl`, because `github.com/go-gl/gl/v4.5-core/gl` unavailable anymore.

Can't compile with open gl 4.5:
```
panic: VersionUnavailable: The requested client API version is unavailable
```

okay, change version to 4.1 and compile again:
```
panic: glBindBuffersBase

goroutine 1 [running, locked to thread]:
main.initializeWindow()
	/Volumes/mac/Users/Maxim/Projects/Voxel-Engine/src/main/main.go:66 +0x243
main.main()
	/Volumes/mac/Users/Maxim/Projects/Voxel-Engine/src/main/main.go:259 +0x1b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

glfw 3.1.1,
go1.4.2 darwin/amd64

**Comment by max107** [comment]
oh, it's my mistake. I set opengl version 4.5, but not change imports.

**Comment by max107** [comment]
All changes: https://github.com/max107/Voxel-Engine/commit/5126f0a05ba5c8be7a443ab93a8e01100c481868

**Comment by allanks** [comment]
GLBindBufferBase for shared storage shader buffers was only made core in opengl version 4.3 and above which will be the cause of the panic. A fix will be to change the buffers to uniform buffer objects which have been core since 3.1.

The only reason they are currently SSBOs is that I could not find enough information on UBOs to set them up

**Comment by allanks** [comment]
Hmm, my previous comment made an incorrect statement, the SSBOs are necessary as the uniform buffers need a set length, whereas the SSBOs can be dynamic

**Comment by max107** [comment]
i think, need add backward compatibility with oldest hardware / software. It's a good point for other developers. My mac support only 4.1 and i can't connect to project because can't run and compile project :)

Sorry for my bad english.

**Comment by allanks** [comment]
I have created a new issue [#46] for this, I am going to extract the opengl stuff into other files so that it can be abstracted behind an interface. After that I it will be possible to create compatibility layers so that anyone can use this software

**Comment by max107** [comment]
thanks!
